name: C++ CI

on:
  push:
    branches:
      - mamba-ready

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Установка пакетов
        run: |
          sudo locale-gen ru_RU
          sudo locale-gen ru_RU.UTF-8
          sudo update-locale

      - name: Плучение списка пул-реквестов mamba-ready
        uses: octokit/request-action@v2.x
        id: list_pull_requests
        with:
          route: GET /repos/${{ github.repository }}/pulls
          state: "open"
          head: "mamba-ready"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Пул-реквест mamba-ready уже создан
        if: contains(steps.list_pull_requests.outputs.data, 'id')==true
        run: |
          echo "Ну и ладно"

      - name: Создаем Пул-реквест mamba-ready
        uses: octokit/request-action@v2.x
        id: create_pull_request
        if: contains(steps.list_pull_requests.outputs.data, 'id')==false
        with:
          route: POST /repos/${{ github.repository }}/pulls
          title: "Auto-generated by octokit/request-action action from mamba.ru"
          head: "mamba-ready"
          base: "master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
